dags/rollout_ic_os_to_subnets.py
Increases robustness against sporadic failures of ic-admin or dre.
=> Retry the unassigned nodes.

rollout-dashboard/doc/api.md, rollout-dashboard/server/src/airflow_client.rs, rollout-dashboard/server/src/frontend_api.rs
The rollout dashboard keeps a local cache of all tasks it has seen, because
retrieving *all* task instances from Airflow is expensive.  We do this
during the first loop, but in subsequent runs, we retrieve tasks that have
updated or modified after the last check's timestamp.  To this, we also add
tasks that have started after the last check.
In addition to that, we now linearize the tasks in case that any of the
retrieved task lists contains the same task, but may have been updated
between requests.  Linearization involves picking, for each task instance
the object with the latest date (be it execution, start or end date).
In addition to that, if the rollout plan is somehow retrieved but marked
empty when the schedule task is complete, we re-retrieve it again.  This
prevents the odd error …
=> Rework local cache to address "not yet computed a rollout plan" issue.

bin/airflow, rollout-dashboard/server/src/airflow_client.rs, rollout-dashboard/server/src/frontend_api.rs, rollout-dashboard/server/src/main.rs
Two things happen in this PR:
1. An endpoint to fetch the internal cache is added, in order to help diagnose any logic errors that may be causing the API to return "not yet computed rollout" for rollouts started during the weekend.
2. The logic of when to fetch the rollout plan is changed to the task evaluation loop.
I cannot reproduce this locally with Airflow so the hope is that item #1 in this PR will help diagnose next week if the problem is not resolved by #2.
=> Attempt to fix / diagnose the "not yet computed rollout" problem.

plugins/operators/ic_os_rollout.py, plugins/sensors/ic_os_rollout.py
Fixes the algorithmic problem we had before that caused no notifications to be sent.
Will be auto-rolled out upon merge.
=> Notify every hour if a rollout task is stalled on waiting for alerts to resolve

plugins/sensors/ic_os_rollout.py
This can be rolled out on the spot.
=> Hide Prometheus query unless explicitly disclosed.

rollout-dashboard/server/Cargo.lock, rollout-dashboard/server/Cargo.toml, rollout-dashboard/server/src/airflow_client.rs, rollout-dashboard/server/src/frontend_api.rs, rollout-dashboard/server/src/main.rs
As per https://dfinity.atlassian.net/browse/DRE-303 and https://dfinity.atlassian.net/browse/DRE-304 , in certain cases where the administrator has intervened in the rollout (via clearing tasks for retry, or marking them as failed, or marking them as successful), the cache gets out of synchronization with the actual Airflow state, because these task changes do not update the task dates (which is what the cache relies on, to prevent transferring tens of megabytes every 5 seconds).
This implements the use of an incremental log parser that fishes out tasks updated in the last update window.  With that, we can deduce when a rollout needs full task update or just certain tasks.
Alas, some tasks do not log updates even when they execute (chiefly the tasks implemented by Airflow logic and null …
=> Fix various problems with rollout dashboard's cache and task processing.

rollout-dashboard/README.md, rollout-dashboard/frontend/src/App.svelte, rollout-dashboard/server/src/frontend_api.rs, rollout-dashboard/server/src/main.rs
* Make the schedule cache structures robust against various corner cases.
* Make the code processing schedule caches much cleaner.
* Mark the cache API endpoint as unstable.
* Add help link to the bottom of the dashboard.
* Minor documentation changes.
=> Various improvements to the dashboard.

plugins/sensors/ic_os_rollout.py
We now tolerate up to 1/3 of nodes that may have changed the version they are running independently from the subnet upgrade (e.g. if a node was offline and came back online, or if it was just added to the subnet)
Here is a [test query](https://grafana.mainnet.dfinity.network/explore?schemaVersion=1&panes=%7B%22oao%22:%7B%22datasource%22:%22P119963096DF10E67%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22sum%28changes%28ic_replica_info%7Bic_subnet%3D%5C%22uzr34-akd3s-xrdag-3ql62-ocgoh-ld2ao-tamcv-54e7j-krwgb-2gm4z-oqe%5C%22%7D%5B1d%5D%29%29%20%3E%20count%20%28ic_replica_info%7Bic_subnet%3D%5C%22uzr34-akd3s-xrdag-3ql62-ocgoh-ld2ao-tamcv-54e7j-krwgb-2gm4z-oqe%5C%22%7D%29%20%2F%203%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P11 …
=> fix: Correct the query if the "other" tECDSA subnet was updated in the last 24h

shared/dfinity/dre.py
to fix:
```
[2024-12-09, 12:06:53 UTC] {subprocess.py:93} INFO -  2024-12-09T12:06:53.957Z INFO  dre::store > Using ic-admin: /home/airflow/.cache/dre-store/ic-admin.revisions/957689f550775c7dfb7767dc2085a7845cf52533/ic-admin
[2024-12-09, 12:06:53 UTC] {subprocess.py:93} INFO - Error: ic-admin failed with non-zero exit code 2 stderr ==>
[2024-12-09, 12:06:53 UTC] {subprocess.py:93} INFO - error: Found argument '--silence-notices' which wasn't expected, or isn't valid in this context
[2024-12-09, 12:06:53 UTC] {subprocess.py:93} INFO - 
[2024-12-09, 12:06:53 UTC] {subprocess.py:93} INFO - 	If you tried to supply `--silence-notices` as a value rather than a flag, use `-- --silence-notices`
[2024-12-09, 12:06:53 UTC] {subprocess.py:93} INFO - 
[2024-12-09, 12:06:53 UTC] {subprocess.py:93} …
```
=> Update ic-admin version

shared/dfinity/dre.py
This PR reverts the hardcoded ic-admin versions because of the issue with glibc.
Tested that ic-admin would work with:
```bash
dre get subnet-list
```
It was performed on ubuntu `20.04` with the following glibc version:
```bash
root@13e031180f1c:/# ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.16) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
=> core: reverting `ic-admin` hardocded versions

.github/workflows/rollout-dashboard.yaml
Also fix the automation to actually run.
=> Restore the condition to publish the rollout dashboard container.

README.md, bin/airflow
- **README Update**: Clarifies that S3 Logging is for production Kubernetes deployments.
- **Script Enhancements**:
- Uses `set -eEuo pipefail` for more robust bash scripting.
- Defines additional utility directories and sets environment variables accordingly.
- Adds functions for installing and configuring 1Password CLI (`install_1pass_cli`, `login_1pass`).
- Sets up Airflow variables and connections using 1Password credentials.
- **User Interaction**: Adds conditional prompt to setup Airflow variables and connections, optional for local runs.
- **Multi-functional Handling**:
- Introduces a check to prevent concurrent Airflow instances.
- Enhances the existing 'unlockdb' functionality to support 'standalone' mode.
- **Command Execution**: Updates execution to use defined utility paths.
=> feat(airflow): improve setup script and add 1Password CLI integration

plugins/operators/gsheets_rollout.py
- Streamline `convert_rollout_week_sheet_name` by replacing regex-based date extraction with direct `strptime` parsing for the format `%Y-%m-%d`.
- Remove redundant fallback logic for parsing dates without a year, focusing on specific date string format.
- Simplify error handling to raise `ValueError` when date parsing fails.
=> refactor(gsheets): simplify date parsing logic

.github/workflows/airflow-content-syncer-container.yaml
After kimerization of Airflow, this file was moved and therefore would not be updated.
=> Fix typo in file path.

.github/workflows/update-k8s-deployments/action.yaml
Updated the commit title format to remove '[nomrbot]' prefix, ensuring clarity and consistency in deployment rollouts.
=> Fix commit title format in update-k8s-deployments action

.github/workflows/update-k8s-deployments/action.yaml
This change updates the `K8S_REPO_BRANCH` variable to dynamically include the repository name using `basename $GITHUB_REPOSITORY`. This ensures that each deployment branch is uniquely named based on the GitHub repository, enhancing organization and reducing potential naming conflicts. No new features are introduced.
=> fix: dynamically generate K8S_REPO_BRANCH name

.github/workflows/airflow-content.yaml, bin/airflow
While we are not ready to upgrade to latest Airflow, testing by using old setuptools (what ships in the Ubuntu 22.04 container) should address pipeline failure.
=> Pipelines are failing because Airflow 2.9.1 contains an issue in its Google provider.

shared/dfinity/dre.py
To get this rolled out, worker containers must be restarted in the ch1-rel1 cluster.
This was a temporary measure now this needs to be reverted.
=> Use latest DRE.

shared/dfinity/dre.py
This allows the default (which is `ask`) not to crash the tool when running it noninteractively.
Fixes this backtrace:
```
Error: IO error: not a terminal
Caused by:
not a terminalError: IO error: not a terminal
Caused by:
not a terminal
Stack backtrace:
0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
1: <dre::forum::impls::Discourse as dre::forum::ForumPostHandler>::forum_post::{{closure}}
2: dre::submitter::Submitter::propose::{{closure}}
3: dre::submitter::Submitter::propose_and_print::{{closure}}
4: <dre::commands::main_command::Subcommands as dre::exe::ExecutableCommand>::execute::{{closure}}
5: dre::main::{{closure}}
6: tokio::runtime::park::CachedParkThread::block_on
7: tokio::runtime::context::runtime::enter_runtime
8: …
```
=> Ask the DRE tool to omit forum post link when upgrading unassigned nodes

.github/workflows/airflow-content.yaml, dags/auto_compute_rollout.py, dags/deploy_ic_os_to_subnet.py, dags/rollout_ic_os_to_api_boundary_nodes.py, dags/rollout_ic_os_to_boundary_nodes.py, dags/rollout_ic_os_to_subnets.py, dags/test_dag.py, plugins/operators/auto_rollout.py, plugins/operators/ic_os_rollout.py, plugins/sensors/ic_os_rollout.py, shared/dfinity/dre.py, shared/dfinity/ic_os_rollout.py, shared/dfinity/ic_types.py, shared/dfinity/rollout_types.py, tests/test_ic_os_rollout.py, tests/test_ic_os_rollout_operators.py, tests/test_plan_generator.py, tests/test_rollout_types.py, tests/test_schedule.py
This work comprises the following parts (as a chain of commits):
* Code quality improvements setting the stage for the feature being added here.
* The main feature being added, which is a flow that implements API boundary nodes rollout as per https://dfinity.atlassian.net/browse/DRE-407 .
Notes:
* To determine if a batch of nodes has upgraded, we issue this Prometheus query:
```
joined = "|".join(boundary_node_ids)
query = (
"sum(ic_orchestrator_info{"
+ f'ic_node=~"{joined}"'
+ "}) by (ic_active_version, ic_subnet)"
)
```
* To determine if a batch of nodes is all healthy, we do this:
```
bns = "|".join(boundary_node_ids)
query = """
sum_over_time(
ALERTS{
ic_node=~"%(bns)s",
severity="page"
}[15m]
)""" % (
{
"bns": bns,
}
)
```
* The current number of boundary nodes is 20, so we start …
=> API boundary nodes rollout.

dags/auto_compute_rollout.py, dags/rollout_ic_os_to_api_boundary_nodes.py, dags/rollout_ic_os_to_subnets.py, plugins/operators/auto_rollout.py, rollout-dashboard/frontend/tsconfig.json, rollout-dashboard/frontend/tsconfig.node.json, shared/dfinity/ic_os_rollout.py, tests/test_schedule.py
Updated the code to use `DEFAULT_GUESTOS_ROLLOUT_PLANS` and `DEFAULT_API_BOUNDARY_NODES_ROLLOUT_PLANS`. Renamed parameters and triggered tasks accordingly. Added support for custom HTML forms for rollout plans.
This finishes https://dfinity.atlassian.net/browse/DRE-407 .
=> Refactor rollout plan dispatcher flow to include GuestOS and API boundary nodes

dags/rollout_ic_os_to_nodes.py
The task ID in the PythonSensor has been renamed to better reflect its purpose, which is now to wait for a specific revision to be elected.
- Updated `task_id` from 'wait_until_nodes_healthy' to 'wait_for_revision_to_be_elected'.
=> Rename task_id from 'wait_until_nodes_healthy' to 'wait_for_revision_to_be_elected'.

rollout-dashboard/frontend/src/App.svelte, rollout-dashboard/frontend/src/lib/ApiBoundaryNodesBatch.svelte, rollout-dashboard/frontend/src/lib/HostOSBatch.svelte, rollout-dashboard/frontend/src/lib/HostOSRollout.svelte, rollout-dashboard/frontend/src/lib/SubnetBatch.svelte
* Prevent text wrap in batch tile.
* If nodes are different, even if they are the same count, show a note to that effect.
* Pills that display the name of each HostOS rollout stage required padding.
* Center loading spinner.  It used to be centered but when it moved to the header, CSS cascading broke that.
=> Cosmetic fixes to rollout dashboard:

plugins/sensors/hostos_rollout.py, shared/dfinity/dre.py
The `--json` argument to dre get elected hostos revisions has (unexpectedly) no effect; we still get revisions as a newline-separated list.  Decode that instead.
Sample error this PR fixes:
```
Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
result = _execute_callable(context=context, **execute_callable_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
return execute_callable(context=context, **execute_callable_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/ba …
```
=> Fix election check for HostOS rollout.

dags/rollout_ic_os_to_nodes.py, plugins/operators/hostos_rollout.py, rollout-dashboard/frontend/src/lib/Alert.svelte, rollout-dashboard/frontend/src/lib/HostOSBatchDetail.svelte, rollout-dashboard/frontend/src/lib/Selectors.svelte, rollout-dashboard/frontend/src/lib/types.ts, rollout-dashboard/server/src/live_state/hostos_rollout.rs, rollout-dashboard/server/src/types.rs, shared/dfinity/rollout_types.py, tests/test_hostos_rollout.py, tests/test_rollout_types.py
This allows us to support node selection predicates like `1 node per subnet except for nodes in datacenter hk4`.
All layers of the stack (rollout, dashboard backend and frontend) have gained this support.  Here is how a demo rollout using this feature looks like:
=> Support for exclusion in HostOS rollout plans.

rollout-dashboard/frontend/src/lib/ApiBoundaryNodesRollout.svelte, rollout-dashboard/frontend/src/lib/GuestOSRollout.svelte, rollout-dashboard/frontend/src/lib/HostOSRollout.svelte, rollout-dashboard/frontend/src/routes/index.svelte
Before, we used to show the paused state at the top.  This did not make much sense, because the association between the infobox and the actual rollout is visually not noticeable.
Now we show the paused infobox within the rectangle of the rollout it affects.  Here is a visual of how that looks like:
A bunch of imports no longer needed have been removed.
=> Rollouts now show paused state within the rollout rectangle.

rollout-dashboard/server/src/airflow_client.rs, rollout-dashboard/server/src/api_server.rs, rollout-dashboard/server/src/live_state/task_sorter.rs, rollout-dashboard/server/src/main.rs, rollout-dashboard/server/src/types.rs
With the feature gate behind a variable which defaults to false, we prevent anyone from retrieving any arbitrary XCom (task instance return value) from the unstable API endpoint, including anything potentially sensitive.
=> Gate unstable API behind variable, and provide XCom retrieval unstable API endpoint.

rollout-dashboard/frontend/src/App.svelte, rollout-dashboard/frontend/src/lib/HostOSBatchDetail.svelte, rollout-dashboard/frontend/src/lib/HostOSRollout.svelte, rollout-dashboard/frontend/src/lib/index.svelte
Speed up rendering of main view by never closing the socket connection to the server.
In a prior iteration, we made the main state socket connection to the server be closed when a batch detail view was navigated into.  This is silly.  Even the batch detail view uses data from it, and it makes no sense to close the connection just to reopen it again.
In this PR, the prior behavior is restored, but this time, we take care to abort the connection once the user navigates away from the app (this should be done by the browser but it pays to pay attention to detail like that).
=> Make returning to the homescreen fast

rollout-dashboard/frontend/src/App.svelte, rollout-dashboard/frontend/src/lib/HostOSBatchDetail.svelte, rollout-dashboard/frontend/src/lib/HostOSRollout.svelte, rollout-dashboard/frontend/src/lib/index.svelte, rollout-dashboard/frontend/src/lib/stores.ts
During reconnection events, we were firing twice the reconnection attempts, causing an exponential increase in memory and an eventual hang of the dashboard.
Fix this.
This goes atop the following PR: https://github.com/dfinity/dre-airflow/pull/178
=> Fix corner case that would cause the dashboard to eat a ton of memory.

airflow-customized/Dockerfile
Part of https://dfinity.atlassian.net/browse/DRE-496 .
This shall not be rolled into production directly, but rather with an upcoming Helm chart change that leverages this container version.
=> Generate a new container for Airflow with version 2.11.0.
