- plugins/operators/ic_os_rollout.py
Reverts dfinity/dre-airflow#44
> Revert "Temporary disable check_plan for hotfix rollout "

- rollout-dashboard/frontend/src/lib/stores.ts
- rollout-dashboard/server/src/airflow_client.rs
- rollout-dashboard/server/src/frontend_api.rs
- rollout-dashboard/server/src/main.rs
- rollout-dashboard/server/src/types.rs
New frontend, looks the same as the previous one, but updates incrementally only.  Deleted rollouts disappear from dashboard, added appear, and updates have much improved in both terms of data usage, and also speed of reporting.  Many update bugs have been fixed too.
> Implement incremental updates.

- rollout-dashboard/frontend/src/App.svelte
- rollout-dashboard/frontend/src/lib/stores.ts
- rollout-dashboard/server/src/airflow_client.rs
- rollout-dashboard/server/src/frontend_api.rs
- rollout-dashboard/server/src/main.rs
Addresses https://dfinity.atlassian.net/browse/DRE-298 .
How it looks like:
If the DAG is broken, a warning message will appear.
> Implement showing rollout state at the top of the rollout list.

- rollout-dashboard/frontend/src/App.svelte
- rollout-dashboard/frontend/src/lib/stores.ts
- rollout-dashboard/frontend/src/lib/types.ts
- rollout-dashboard/server/src/api_server.rs
- rollout-dashboard/server/src/lib.rs
- rollout-dashboard/server/src/live_state/mod.rs
- rollout-dashboard/server/src/live_state/python.rs
- rollout-dashboard/server/src/main.rs
- rollout-dashboard/server/src/types.rs
There is no functional change in this PR.
> Refactor code base and types, preserving compatibility with older clients.

- plugins/operators/gsheets_rollout.py
My previous PR https://github.com/dfinity/dre-airflow/pull/64 erroneously does not support subnets without features enabled
> fix: Allow no enabled features on a subnet

- plugins/sensors/ic_os_rollout.py
[Example query](https://grafana.mainnet.dfinity.network/explore?schemaVersion=1&panes=%7B%22r54%22:%7B%22datasource%22:%22P119963096DF10E67%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%28%5Cn%20%20sum%28changes%28%28ic_replica_info%7Bic_subnet%3D%5C%22uzr34-akd3s-xrdag-3ql62-ocgoh-ld2ao-tamcv-54e7j-krwgb-2gm4z-oqe%5C%22%7D%29%5B1d%5D%29%20or%20vector%280%29%29%5Cn%20%20%3E%3D%5Cn%20%20scalar%28job_ic_icsubnet:up:count%7Bjob%3D%5C%22replica%5C%22,%20ic_subnet%3D%5C%22uzr34-akd3s-xrdag-3ql62-ocgoh-ld2ao-tamcv-54e7j-krwgb-2gm4z-oqe%5C%22%7D%20%2F%203%29%5Cn%29%20or%200%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P119963096DF10E67%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%2 …
> fix: Update query logic to tolerate subnet updates and handle zero results

- .github/workflows/rollout-dashboard.yaml
- .github/workflows/update-k8s-deployments/action.yaml
- rollout-dashboard/README.md
Related PR: https://github.com/dfinity-ops/k8s/pull/703
> Auto-create upgrade PRs in K8s.

- .github/workflows/update-k8s-deployments/action.yaml
> It's a property.

- plugins/operators/auto_rollout.py
This ensures normal DAG triggers have a short and sweet name compatible with prior ones.
> Name any retriggered DAG with a special name format.

- .github/workflows/airflow-content-syncer-container.yaml
- .github/workflows/airflow-content.yaml
- .github/workflows/airflow-customized-container.yaml
- .github/workflows/publish/action.yaml
- .github/workflows/rollout-dashboard.yaml
- .github/workflows/update-k8s-deployments/action.yaml
- bin/airflow
In addition, the logic to update the rollout PR has been updated to be more precise about what PRs to update on the k8s repo.
This does not require a publish of the containers.
> Permit manual dispatch of Github actions

- shared/dfinity/dre.py
It's somewhat likely that we will get meaningful backtraces from this.
Once merged this will be automatically rolled out in the next 5 to 10 minutes.
> Run the DRE command line utility using RUST_BACKTRACE=1.

- shared/dfinity/dre.py
Otherwise this complains about not a terminal too.
> Omit forum post link for deployment of new GuestOS versions.

- .github/workflows/update-k8s-deployments/action.yaml
> Reduce fetch depth, sanitize branch name, and add support for Github workflow summaries.

- rollout-dashboard/frontend/src/lib/Rollout.svelte
Fixes https://dfinity.atlassian.net/browse/DRE-301 .
> Color rollouts based on their state.

- README.md
- bin/airflow
- dags/target_topology.py
- plugins/operators/target_topology.py
The credentials have  been updated to work with this project.
> feat: daily testing run of target topology tool

- README.md
- bin/airflow
- dags/target_topology.py
- plugins/operators/target_topology.py
Includes an actual check of python version instead of relying on version to be 3.12.
> fix: moving to wasabi for artifacts of runs

- shared/dfinity/dre.py
> Fix get blessed hostos versions.

- plugins/sensors/ic_os_rollout.py
Changes weekday comparison to week number comparison in `WaitForOtherDAGs`.
> Fix simultaneous rollout execution prevention.

- plugins/operators/hostos_rollout.py
This prevents the rollout batch from attempting to upgrade nodes that were attempted in the prior batches, but did not upgrade.
> Exclude nodes already rolled out prior to computing which nodes to roll out to.

- plugins/sensors/hostos_rollout.py
- shared/dfinity/rollout_types.py
This information will be used in the frontend.
> Tell Airflow to store the alerting and upgrade status of HostOS nodes.

- rollout-dashboard/Dockerfile
- rollout-dashboard/server/src/airflow_client.rs
- rollout-dashboard/server/src/api_server.rs
- rollout-dashboard/server/src/live_state/api_boundary_nodes_rollout.rs
- rollout-dashboard/server/src/live_state/guestos_rollout.rs
- rollout-dashboard/server/src/live_state/hostos_rollout.rs
- rollout-dashboard/server/src/live_state/log_inspector.rs
- rollout-dashboard/server/src/live_state/mod.rs
- rollout-dashboard/server/src/live_state/plan.rs
- rollout-dashboard/server/src/live_state/python.rs
- rollout-dashboard/server/src/live_state/task_sorter.rs
- rollout-dashboard/server/src/main.rs
* Implement a variety of cargo clippy fixes.
* Reduce redundancy in SSE guard code.
* Switch *runtime* image to Fedora 42 instead of Debian Bookworm.
> Fixes to diagnose the crash.

- rollout-dashboard/frontend/src/lib/HostOSBatch.svelte
Add hover/focus styles for HostOSBatch links on hover/focus for better user interaction with HostOSBatch links, enhancing overall UI experience.
> Provide visual cues that batches in HostOS are clickable.

- rollout-dashboard/server/src/live_state/mod.rs
When a DAG goes missing because it's broken, we need to:
* fill in the correct broken state for that DAG
* gracefully handle the error by simply not querying any of its DAG runs
This PR accomplishes that.
> Handle corner case of missing DAG.

- dags/defaults.py
- tests/test_hostos_rollout.py
Under advisement from @r-birkner .
> Update HostOS rollout defaults
